{% set name = "macports-legacy-support" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/macports/macports-legacy-support/archive/v{{ version }}.tar.gz
  sha256: 6544c48e25c768b1f2780398b2f7c375ef9d4ba5c54f482a175af14ec7b488e4

build:
  number: 0
  skip: true  # [not osx]
  script: make PREFIX=$PREFIX CFLAGS="$CPPFLAGS $CFLAGS" LDFLAGS="$LDFLAGS" install
  run_exports:
    # Let's trust them.
    # xref: https://ports.macports.org/port/legacy-support/summary
    - {{ pin_subpackage('macports-legacy-support') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - test -f ${PREFIX}/include/LegacySupport/time.h
    - test -f ${PREFIX}/lib/libMacportsLegacySupport${SHLIB_EXT}

about:
  home: https://github.com/macports/macports-legacy-support
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Installs wrapper headers to add missing functionality to legacy OSX versions.

extra:
  recipe-maintainers:
    - nehaljwani
