{% set name = "macports-legacy-support" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/macports/macports-legacy-support/archive/v{{ version }}.tar.gz
  sha256: 97135e9fbe27283ae3eb79c778e9757af29d1177481764ffe4e6f5dfdc360a0e

build:
  number: 0
  skip: true  # [not osx]
  script: make PREFIX=$PREFIX CFLAGS="$CPPFLAGS $CFLAGS" LDFLAGS="$LDFLAGS" install
  run_exports:
    # Let's trust them.
    # xref: https://ports.macports.org/port/legacy-support/summary
    - {{ pin_subpackage('macports-legacy-support') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make

test:
  commands:
    - test -f ${PREFIX}/include/LegacySupport/time.h
    - test -f ${PREFIX}/lib/libMacportsLegacySupport${SHLIB_EXT}

about:
  home: https://github.com/macports/macports-legacy-support
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Installs wrapper headers to add missing functionality to legacy OSX versions.

extra:
  recipe-maintainers:
    - nehaljwani
